# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\tscheduler\"\xb8\x01\n\x05Shift\x12\x30\n\x0f\x64\x61y_of_the_week\x18\x01 \x01(\x0e\x32\x17.scheduler.DayOfTheWeek\x12+\n\nstart_hour\x18\x02 \x01(\x0e\x32\x17.scheduler.HourOfTheDay\x12)\n\x08\x65nd_hour\x18\x03 \x01(\x0e\x32\x17.scheduler.HourOfTheDay\x12%\n\x08\x65mployee\x18\x04 \x01(\x0b\x32\x13.scheduler.Employee\"\x87\x01\n\x08\x45mployee\x12\x13\n\x0b\x65mployee_id\x18\x01 \x01(\t\x12\x10\n\x08\x62\x61se_pay\x18\x02 \x01(\x05\x12(\n\nshift_list\x18\x03 \x03(\x0b\x32\x14.scheduler.ShiftList\x12\x15\n\rweekend_bonus\x18\x04 \x01(\x05\x12\x13\n\x0bnight_bonus\x18\x05 \x01(\x05\"\x1f\n\tShiftList\x12\x12\n\nshift_name\x18\x01 \x01(\t*v\n\x0c\x44\x61yOfTheWeek\x12\n\n\x06UKNOWN\x10\x00\x12\n\n\x06MONDAY\x10\x01\x12\x0b\n\x07TUESDAY\x10\x02\x12\r\n\tWEDNESDAY\x10\x03\x12\x0c\n\x08THURSDAY\x10\x04\x12\n\n\x06\x46RIDAY\x10\x05\x12\x0c\n\x08SATURDAY\x10\x06\x12\n\n\x06SUNDAY\x10\x07*\xc2\x02\n\x0cHourOfTheDay\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x12\t\n\x05THREE\x10\x03\x12\x08\n\x04\x46OUR\x10\x04\x12\x08\n\x04\x46IVE\x10\x05\x12\x07\n\x03SIX\x10\x06\x12\t\n\x05SEVEN\x10\x07\x12\t\n\x05\x45IGHT\x10\x08\x12\x08\n\x04NINE\x10\t\x12\x07\n\x03TEN\x10\n\x12\n\n\x06\x45LEVEN\x10\x0b\x12\n\n\x06TWELVE\x10\x0c\x12\x0c\n\x08THIRTEEN\x10\r\x12\x0c\n\x08\x46OURTEEN\x10\x0e\x12\x0b\n\x07\x46IFTEEN\x10\x0f\x12\x0b\n\x07SIXTEEN\x10\x10\x12\r\n\tSEVENTEEN\x10\x11\x12\x0c\n\x08\x45IGHTEEN\x10\x12\x12\x0c\n\x08NINETEEN\x10\x13\x12\n\n\x06TWENTY\x10\x14\x12\r\n\tTWENTYONE\x10\x15\x12\r\n\tTWENTYTWO\x10\x16\x12\x0f\n\x0bTWENTYTHREE\x10\x17\x12\x0e\n\nTWENTYFOUR\x10\x18\x62\x06proto3')

_DAYOFTHEWEEK = DESCRIPTOR.enum_types_by_name['DayOfTheWeek']
DayOfTheWeek = enum_type_wrapper.EnumTypeWrapper(_DAYOFTHEWEEK)
_HOUROFTHEDAY = DESCRIPTOR.enum_types_by_name['HourOfTheDay']
HourOfTheDay = enum_type_wrapper.EnumTypeWrapper(_HOUROFTHEDAY)
UKNOWN = 0
MONDAY = 1
TUESDAY = 2
WEDNESDAY = 3
THURSDAY = 4
FRIDAY = 5
SATURDAY = 6
SUNDAY = 7
UNKNOWN = 0
ONE = 1
TWO = 2
THREE = 3
FOUR = 4
FIVE = 5
SIX = 6
SEVEN = 7
EIGHT = 8
NINE = 9
TEN = 10
ELEVEN = 11
TWELVE = 12
THIRTEEN = 13
FOURTEEN = 14
FIFTEEN = 15
SIXTEEN = 16
SEVENTEEN = 17
EIGHTEEN = 18
NINETEEN = 19
TWENTY = 20
TWENTYONE = 21
TWENTYTWO = 22
TWENTYTHREE = 23
TWENTYFOUR = 24


_SHIFT = DESCRIPTOR.message_types_by_name['Shift']
_EMPLOYEE = DESCRIPTOR.message_types_by_name['Employee']
_SHIFTLIST = DESCRIPTOR.message_types_by_name['ShiftList']
Shift = _reflection.GeneratedProtocolMessageType('Shift', (_message.Message,), {
  'DESCRIPTOR' : _SHIFT,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.Shift)
  })
_sym_db.RegisterMessage(Shift)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEE,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.Employee)
  })
_sym_db.RegisterMessage(Employee)

ShiftList = _reflection.GeneratedProtocolMessageType('ShiftList', (_message.Message,), {
  'DESCRIPTOR' : _SHIFTLIST,
  '__module__' : 'scheduler_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.ShiftList)
  })
_sym_db.RegisterMessage(ShiftList)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DAYOFTHEWEEK._serialized_start=388
  _DAYOFTHEWEEK._serialized_end=506
  _HOUROFTHEDAY._serialized_start=509
  _HOUROFTHEDAY._serialized_end=831
  _SHIFT._serialized_start=31
  _SHIFT._serialized_end=215
  _EMPLOYEE._serialized_start=218
  _EMPLOYEE._serialized_end=353
  _SHIFTLIST._serialized_start=355
  _SHIFTLIST._serialized_end=386
# @@protoc_insertion_point(module_scope)
